### PR TITLE
add support for incremental S3 uploads

### PR DESCRIPTION
**Pull request by fehwalker**
fix for issue #44

### CODE REVIEW

**Comment by fehwalker** [comment]
After looking a bit I found that the etag method on s3 objects returns the ms5 sum (plus quotes, which I stripped). Added an incremental flag to turn the feature on/off.

**Comment by imathis** [comment]
Thanks! Have you been able to verify that this works?

**Comment by fehwalker** [comment]
I'm using it with a test copy of my little blog I'm trying to get working in octopress 3, it only uploads changed files. It's muuuch faster to just pass metadata than push all files over my connection (DSL), especially some of the larger images I have in blog entries.

**Comment by imathis** [comment]
Thanks for the update. I'm going to give this a whirl and if it looks good I'll merge it. Thanks for your work on this!

**Comment by imathis** [comment]
Thanks! I merged it in and released 1.1.0.

**Comment by magikid** [comment]
Does merging this resolve issue #44? Can it be closed?

**Comment by imathis** [comment]
@magikid I believe so. Thanks for the heads up.

**Pull request merged**
